from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
from model import *
from PyQt5 import QtCore, QtGui, QtWidgets
from explore import *
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 600)
        MainWindow.setWindowTitle("loktra-volterra")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 301, 405))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.alpha_inpuit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.alpha_inpuit.setObjectName("alpha_inpuit")
        self.gridLayout.addWidget(self.alpha_inpuit, 2, 1, 1, 1)
        self.delta_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.delta_input.setObjectName("delta_input")
        self.gridLayout.addWidget(self.delta_input, 4, 1, 1, 1)
        self.x0_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.x0_input.setObjectName("x0_input")
        self.gridLayout.addWidget(self.x0_input, 6, 1, 1, 1)
        self.betha_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.betha_label.setObjectName("betha_label")
        self.gridLayout.addWidget(self.betha_label, 3, 0, 1, 1)
        self.gamma_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.gamma_label.setObjectName("gamma_label")
        self.gridLayout.addWidget(self.gamma_label, 5, 0, 1, 1)
        self.y0_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.y0_input.setObjectName("y0_input")
        self.gridLayout.addWidget(self.y0_input, 7, 1, 1, 1)
        self.beta_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.beta_input.setObjectName("beta_input")
        self.gridLayout.addWidget(self.beta_input, 3, 1, 1, 1)
        self.alpha_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.alpha_label.setObjectName("alpha_label")
        self.gridLayout.addWidget(self.alpha_label, 2, 0, 1, 1)
        self.x0_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.x0_label.setObjectName("x0_label")
        self.gridLayout.addWidget(self.x0_label, 6, 0, 1, 1)
        self.gamma_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.gamma_input.setObjectName("gamma_input")
        self.gridLayout.addWidget(self.gamma_input, 5, 1, 1, 1)
        self.delta_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.delta_label.setObjectName("delta_label")
        self.gridLayout.addWidget(self.delta_label, 4, 0, 1, 1)
        self.y0_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.y0_label.setObjectName("y0_label")
        self.gridLayout.addWidget(self.y0_label, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lv_img = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lv_img.setText("")
        self.lv_img.setPixmap(QtGui.QPixmap("./imagenes/loktra-volterra.png"))
        self.lv_img.setObjectName("lv_img")
        self.verticalLayout.addWidget(self.lv_img)
        self.t_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.t_label.setObjectName("t_label")
        self.verticalLayout.addWidget(self.t_label)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.t_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.t_2.setObjectName("t_2")
        self.gridLayout_4.addWidget(self.t_2, 0, 1, 1, 1)
        self.tv_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tv_label.setObjectName("tv_label")
        self.gridLayout_4.addWidget(self.tv_label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.calcular_push = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calcular_push.setObjectName("calcular_push")
        self.verticalLayout.addWidget(self.calcular_push)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 10, 447, 176))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.visualization_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.visualization_label.setObjectName("visualization_label")
        self.verticalLayout_2.addWidget(self.visualization_label)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.depredadorv_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.depredadorv_label.setObjectName("depredadorv_label")
        self.gridLayout_5.addWidget(self.depredadorv_label, 1, 0, 1, 1)
        self.presav_inf = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.presav_inf.setObjectName("presav_inf")
        self.gridLayout_5.addWidget(self.presav_inf, 1, 1, 1, 1)
        self.depredadorv_inf = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.depredadorv_inf.setObjectName("depredadorv_inf")
        self.gridLayout_5.addWidget(self.depredadorv_inf, 0, 1, 1, 1)
        self.tf_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.tf_label.setObjectName("tf_label")
        self.gridLayout_5.addWidget(self.tf_label, 2, 0, 1, 1)
        self.presav_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.presav_label.setObjectName("presav_label")
        self.gridLayout_5.addWidget(self.presav_label, 0, 0, 1, 1)
        self.t = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.t.setObjectName("t")
        self.gridLayout_5.addWidget(self.t, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(359, 209, 461, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.calcular_push_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.calcular_push_2.setObjectName("calcular_push_2")
        self.calcular_push_2.setText("calcular")
        self.gridLayout_5.addWidget(self.calcular_push_2, 3, 1, 1, 1)

        self.graphic = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.graphic.setContentsMargins(0, 0, 0, 0)
        self.graphic.setObjectName("graphic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 831, 24))
        self.menuBar.setObjectName("menuBar")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #crear grafica de la ecuación 
        self.figure=Figure()
        self.canvas=FigureCanvas(self.figure)
        self.graphic.addWidget(self.canvas)
        #self.toolbar=NavigationToolbar(self.canvas,parent=None)
        #self.graphic.addWidget(self.toolbar)
        self.visualizar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.visualizar.setText("visualizar grafico")
        self.graphic.addChildWidget(self.visualizar)
        self.visualizar.setFixedSize(150, 40)
        self.calcular_push.clicked.connect(lambda:self.plot_ecuation())
        self.calcular_push_2.clicked.connect(lambda:self.change_values())
        self.visualizar.clicked.connect(lambda:self.show_visualization())

    def show_visualization(self):
        show_graph(self.ca.return_values())
        
    def plot_ecuation(self):
        alpha=float(self.alpha_inpuit.text())
        beta=float(self.beta_input.text())
        delta=float(self.delta_input.text())
        gamma=float(self.gamma_input.text())
        x_1=float(self.x0_input.text())
        y_1=float(self.y0_input.text())
        tf=float(self.t_2.text())
        self.ca=calculate(alpha, beta, delta, gamma, x_1, y_1, tf, [self.figure])
        self.canvas.draw()
        self.figure.clear()

    def change_values(self): 
        input_val=int(self.t.text())
        self.depredadorv_inf.setText(str(self.ca.select_vals(input_val)[1]))
        self.presav_inf.setText(str(self.ca.select_vals(input_val)[0]))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.betha_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">beta</span></p></body></html>"))
        self.gamma_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">gamma</span></p></body></html>"))
        self.alpha_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">alpha</span></p></body></html>"))
        self.x0_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">x0 (presa inicial )</span></p></body></html>"))
        self.delta_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">delta</span></p></body></html>"))
        self.y0_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">y0 (depredador inicial )</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">variables</span></p></body></html>"))
        self.t_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">tiempo final</span></p></body></html>"))
        self.tv_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">tf</span></p></body></html>"))
        self.calcular_push.setText(_translate("MainWindow", " Calcular"))
        self.visualization_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">visualización de las poblaciones</span></p></body></html>"))
        self.depredadorv_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Depredador</span></p></body></html>"))
        self.presav_inf.setText(_translate("MainWindow", "0"))
        self.depredadorv_inf.setText(_translate("MainWindow", "0"))
        self.tf_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">tiempo</span></p></body></html>"))
        self.presav_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Presa</span></p></body></html>"))
        #self.menuautomata.setTitle(_translate("MainWindow", "automata")).
